export const WEATHER_DETAIL_REQUEST="WEATHER_DETAIL_REQUEST"
export const WEATHER_DETAIL_SUCCESS="WEATHER_DETAIL_SUCCESS"
export const WEATHER_DETAIL_FAIL="WEATHER_DETAIL_FAIL"
export const WEATHER_DETAIL_RESET="WEATHER_DETAIL_REQUEST"

